name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: false
          fetch-depth: 1

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Create deployment directory
        run: |
          # Create a clean deployment directory
          rm -rf deploy
          mkdir -p deploy
          
          # Create .nojekyll file first to prevent Jekyll processing
          touch deploy/.nojekyll
          
          # Copy only the necessary files from hpnextwave/html directory
          cp -r hpnextwave/html/* deploy/
          
          # Copy CNAME file if it exists
          if [ -f "CNAME" ]; then
            cp CNAME deploy/
          fi
          
          # Debug: Show final directory structure
          echo "Final directory structure:"
          find deploy -type f

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'deploy'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 