name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: false
          fetch-depth: 1

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Create deployment directory
        run: |
          # Create a clean deployment directory
          rm -rf deploy
          mkdir -p deploy
          
          # Create .nojekyll file first to prevent Jekyll processing
          touch deploy/.nojekyll
          
          # Copy only the necessary files from hpnextwave/html directory
          echo "Copying files from hpnextwave/html directory..."
          if [ -d "hpnextwave/html" ]; then
            # Copy HTML files
            cp hpnextwave/html/*.html deploy/
            
            # Copy assets directory if it exists
            if [ -d "hpnextwave/html/assets" ]; then
              cp -r hpnextwave/html/assets deploy/
            else
              echo "Warning: assets directory not found"
            fi
          else
            echo "Error: hpnextwave/html directory not found"
            exit 1
          fi
          
          # Copy CNAME file if it exists
          if [ -f "CNAME" ]; then
            echo "Copying CNAME file..."
            cp CNAME deploy/
          else
            echo "Warning: CNAME file not found"
          fi
          
          # Debug: Show final directory structure
          echo "Final directory structure:"
          find deploy -type f

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'deploy'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 